window.getCharacters = function () {
    return {
        "Mulan": { cname: "花木兰", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Mulan.jpeg", blurb: "Folk heroine who disguised herself as a man to fight in her father's place against nomadic hordes", gender: "female", category: "Historical" },
        "Wukong": { cname: "孙悟空", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Wukong.jpeg", blurb: "Also known as the Monkey King from Journey to the West; he has several supernatural abilities and is known as a bit of a trickster  ", group: "Journey to the West", gender: "male", category: "Literary" },
        "Nezha": { cname: "哪吒", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Nezha.jpeg", blurb: "A taoist protection deity often show flying in the sky on wind fire wheels", gender: "male", category: "Literary" },
        "Chang E": { cname: "嫦娥", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Chang E.jpeg", blurb: "The moon goddess, known for her ethereal beauty and the white rabbit companion", gender: "female", category: "Creation Myth" },
        "Houyi": { cname: "后羿", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Houyi.jpeg", blurb: "A legendary archer of divine skill, famed for shooting down nine of the ten suns that scorched the earth and for his love story with Chang'e", gender: "male", category: "Creation Myth" },
        "Cangjie": { cname: "仓颉", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Cangjie.jpeg", blurb: "A legendary figure credited with the invention of Chinese characters, often depicted with four eyes, symbolizing his ability to observe the patterns of nature that inspired writing.", gender: "male", category: "Creation Myth" },
        "Baigu Jing": { cname: "白骨精", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Baigu Jing.jpeg", blurb: "The malevolent White Bone Spirit from Journey to the West, known for her ability to shapeshift into alluring human forms to deceive and capture the Tang Monk", gender: "female", category: "Literary" },
        "Zhu Bajie": { cname: "猪八戒", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Zhu Bajie.jpeg", blurb: "Also known as Pigsy from Journey to the West, a former celestial marshal banished to Earth and reborn with the head of a pig. A loyal companion of the Tang monk known for his gluttony and flaws", gender: "male", category: "Literary" },
        "Tang Sanzang": { cname: "唐三藏", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Tang Sanzang.jpeg", blurb: "A Buddhist monk from Journey to the West, on a perilous pilgrimage to India for scriptures. Despite naivety, he's steadfast in faith and protected by his disciples.", gender: "male", category: "Literary" },
        "Bai Suzhen": { cname: "白素贞", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Bai Suzhen.jpeg", blurb: "The White Snake Spirit, is a powerful and compassionate immortal from Chinese folklore, known for her deep love for a human scholar.", gender: "female", category: "Literary" },
        "Hong Haier": { cname: "红孩儿", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Hong Haier.jpeg", blurb: "Son of the Bull Demon King and Princess Iron Fan from Journey to the West, he possesses Samadhi True Fire, allowing him to control fire of all forms", gender: "male", category: "Literary" },
        "Sha Wujing": { cname: "沙悟净", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Sha Wujing.jpeg", blurb: " Also known as Sandy from Journey to the West, a former celestial general banished to Earth. A disciple of Tang Sanzang, known for his steadfast nature and wielding the Crescent Moon Spade.", gender: "male", category: "Literary" },
        "Niu Mo Wang": { cname: "牛魔王", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Niu Mo Wang.jpeg", blurb: "The Bull Demon King from Journey to the West, is a powerful figure who tried to stop Tang Sanzang", gender: "male", category: "Literary" },
        "Tieshan Gongzhu": { cname: "铁扇公主", avatarURL: "https://tralinge.github.io/ChineseDictionary.github.io/characters/Tieshan Gongzhu.jpeg", blurb: "Also known as Princess Iron Fan from Journey to the West, her signature weapon is the Iron Fan, a large magical fan that can summon powerful winds, and even typhoons", gender: "female", category: "Literary" },
    };
};
